[Globals]
; xrdp.ini file version number - modified from debian 13
ini_version=1

fork=true
port=3389
use_vsock=false
tcp_nodelay=true
tcp_keepalive=true
#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768
security_layer=negotiate
crypt_level=high

; ssl configuration
certificate=
key_file=
ssl_protocols=TLSv1.2, TLSv1.3

autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
#hidelogwindow=true
max_bpp=32
new_cursors=true
use_fastpath=both
#require_credentials=true
#enable_token_login=true
#pamerrortxt=change your password according to policy at http://url

#black=000000
grey=e1e1e1
dark_grey=b4b4b4
blue=0078d7
dark_blue=0078d7
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72

#fv1_select=130:sans-18.fv1,0:sans-10.fv1
#default_dpi=96

; configure login screen
#ls_title=My Login Title
ls_top_window_bg_color=003057
ls_width=350
ls_height=360
ls_bg_color=f0f0f0
#ls_background_image=
#ls_background_transform=none
; login logo
ls_logo_filename=
ls_logo_transform=scale
ls_logo_width=250
ls_logo_height=110
ls_logo_x_pos=55
ls_logo_y_pos=35

; for positioning labels such as username, password etc
ls_label_x_pos=30
ls_label_width=68

; for positioning text and combo boxes next to above labels
ls_input_x_pos=110
ls_input_width=210

; y pos for first label and combo box
ls_input_y_pos=158

; OK button
ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=308
ls_btn_ok_width=85
ls_btn_ok_height=30

; Cancel button
ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=308
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
; Note: Log levels can be any of: core, error, warning, info, debug, or trace
LogFile=xrdp.log
LogLevel=INFO
EnableSyslog=true
#SyslogLevel=INFO
#EnableConsole=false
#ConsoleLevel=INFO
#EnableProcessId=false

[LoggingPerLogger]
; Note: per logger configuration is only used if xrdp is built with
; --enable-devel-logging
#xrdp.c=INFO
#main()=INFO

[Channels]
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true

;
; Session types
;

[AICODE]
name=AICODE
lib=libvnc.so
ip=127.0.0.1
#port=ask5900
port=5910
username=na
password=ask
#pamusername=asksame
#pampassword=asksame
#delay_ms=2000

